version: '3'
services:
  nginx:
    image: ${NGINX_IMAGE_NAME}
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - "./etc/nginx/app_vhost.conf:/etc/nginx/conf.d/app_vhost.conf"
      - "./etc/ssl:/etc/ssl"
      - "./etc/log:/var/log/nginx"
      - "./public:/var/www/public"
    ports:
      - "8000:80"
      - "4443:443"
    restart: always
    depends_on:
      - php
      - database
  php:
    image: ${PHP_IMAGE_NAME}
    container_name: ${PHP_CONTAINER_NAME}
    restart: always
    volumes:
      - "./:/var/www"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - database
  pma:
    image: ${PMA_IMAGE_NAME}
    container_name: ${PMA_CONTAINER_NAME}
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONTAINER_NAME}
    restart: always
    depends_on:
      - database
  database:
    image: ${DB_IMAGE_NAME}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8919:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
